Pin version of postgres provider so that it still raises exception: captured by test
FAILED tests/operators/test_local.py::test_run_operator_dataset_emission_fails - Failed: DID NOT RAISE <class 'cosmos.exceptions.AirflowCompatibilityError'>