Add default group_id to init params (#399)
## Description

When attempting to override the `group_id` parameter of a DbtTaskGroup,
I get the following error:

```text
TypeError: __init__() got multiple values for argument 'group_id'
```

## Related Issue(s)
closes #398 

## Breaking Change?

There are no breaking changes with this PR

## Checklist

- [x] I have made corresponding changes to the documentation (if
required)
- [x] I have added tests that prove my fix is effective or that my
feature works

Co-authored-by: Julian LaNeve <lanevejulian@gmail.com>