Set CosmosPlugin to None for airflow 3 (#1698)
Interestingly, while working on PR #1692, I didn’t encounter the
following error initially. However, something in my environment must
have changed—possibly related to the Airflow 3 setup—because I’m now
seeing a plugin load error in the `airflow standalone` logs when using a
Hatch-managed Airflow 3 environment:

```
dag-processor | [2025-04-25T18:51:24.537+0530] {plugins_manager.py:262} ERROR - Failed to import plugin cosmos
dag-processor | Traceback (most recent call last):
dag-processor | File "/Users/pankajkoti/Library/Application Support/hatch/env/virtual/astronomer-cosmos/D9FI7Men/tests.py3.9-3.0-1.9/lib/python3.9/site-packages/airflow/plugins_manager.py", line 254, in load_entrypoint_plugins
dag-processor | plugin_class = entry_point.load()
dag-processor | File "/Users/pankajkoti/Library/Application Support/hatch/env/virtual/astronomer-cosmos/D9FI7Men/tests.py3.9-3.0-1.9/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 213, in load
dag-processor | return functools.reduce(getattr, attrs, module)
dag-processor | AttributeError: module 'cosmos.plugin' has no attribute 'CosmosPlugin'
```

While this doesn’t block DAG execution or general Airflow usage, I
believe it’s still worthwhile to iterate on PR #1692 and explicitly set
the plugin to `None` for Airflow 3.x. This avoids the plugin load error
altogether.

With that change in place, the error is resolved, and the environment
works seamlessly with both Airflow 2 and Airflow 3. I’ve also added a
basic sanity check to ensure that CosmosPlugin is either None or
properly initialized, depending on the Airflow version in use.

related: #1685