Fix 'Unable to find the dbt executable: dbt' error
Since Cosmos 1.2.2 users who used Cosmos with ExecutionMode.LOCAL specifying:
```
execution_config = ExecutionConfig(
    dbt_executable_path = f"{os.environ['AIRFLOW_HOME']}/dbt_venv/bin/dbt",
)
```

Started facing the issue:
```
Broken DAG: [/usr/local/airflow/dags/my_example.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 178, in load
    self.load_via_dbt_ls()
  File "/usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py", line 233, in load_via_dbt_ls
    raise CosmosLoadDbtException(f"Unable to find the dbt executable: {self.dbt_cmd}")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to find the dbt executable: dbt
```

As reported in the Airflow #airflow-astronomer Slack channel:
https://apache-airflow.slack.com/archives/C03T0AVNA6A/p1699584315506629

This PR solves the issue.