Fix `dag.test()` for Airflow 3.1+ by syncing DAG to database (#2037)
Airflow 3.1+ requires DagVersion and DagModel records before calling
`dag.test()`.

[Example
failure:](https://github.com/astronomer/astronomer-cosmos/actions/runs/18523664806/job/52789291341#step:7:6713)

```
FAILED tests/test_example_dags.py::test_example_dag[example_cosmos_cleanup_dag] - airflow.exceptions.AirflowException: Cannot create DagRun for DAG example_cosmos_cleanup_dag because the dag is not serialized
FAILED tests/test_example_dags.py::test_example_dag[example_cosmos_dbt_build] - airflow.exceptions.AirflowException: Cannot create DagRun for DAG example_cosmos_dbt_build because the dag is not serialized
FAILED tests/test_example_dags.py::test_async_example_dag_without_setup_task - airflow.exceptions.AirflowException: Cannot create DagRun for DAG simple_dag_async because the dag is not serialized
```

Used `sync_bag_to_db()` to create these records, matching the approach
used by Airflow's CLI `dag test` command.

[Example
run](https://github.com/astronomer/astronomer-cosmos/actions/runs/18574691228/job/52957128514?pr=2036#step:7:1623)
on a different branch (branched off of @tatiana 's
[`af-31`](https://github.com/astronomer/astronomer-cosmos/pull/1980):
[`dag-test-backcompat`](https://github.com/astronomer/astronomer-cosmos/pull/2036))
which runs `dag.test` with Airflow 3.1 .
```
tests/test_example_dags.py::test_example_dag[cosmos_manifest_example] PASSED [ 61%]
tests/test_example_dags.py::test_example_dag[example_taskflow_project_config] PASSED [ 62%]
tests/test_example_dags.py::test_example_dag[example_multiple_parents_test] PASSED [ 62%]
tests/test_example_dags.py::test_example_dag[user_defined_profile] PASSED [ 63%]
tests/test_example_dags.py::test_example_dag[customized_cosmos_dag] PASSED [ 64%]
tests/test_example_dags.py::test_example_dag[basic_cosmos_dag] PASSED    [ 65%]
tests/test_example_dags.py::test_example_dag[cosmos_profile_mapping] PASSED [ 66%]
tests/test_example_dags.py::test_example_dag[basic_cosmos_task_group] PASSED [ 66%]
tests/test_example_dags.py::test_example_dag[example_duckdb_dag] PASSED  [ 67%]
tests/test_example_dags.py::test_example_dag[example_model_version] PASSED [ 68%]
tests/test_example_dags.py::test_example_dag[cosmos_callback_dag] PASSED [ 69%]
tests/test_example_dags.py::test_example_dag[example_operators] PASSED   [ 70%]
```