Try to fix Sphinx issue in the main branch
```
Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/sphinx/config.py", line 601, in eval_config_file
          exec(code, namespace)  # NoQA: S102
          ^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/docs/conf.py", line 7, in <module>
          from docs.generate_mappings import generate_mapping_docs  # noqa: E402
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/docs/generate_mappings.py", line 13, in <module>
          from cosmos.profiles import BaseProfileMapping, profile_mappings
        File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/__init__.py", line 10, in <module>
          from cosmos import settings
        File "/home/runner/work/astronomer-cosmos/astronomer-cosmos/cosmos/settings.py", line 7, in <module>
          import airflow
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/airflow/__init__.py", line 79, in <module>
          settings.initialize()
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/airflow/settings.py", line 698, in initialize
          LOGGING_CLASS_PATH = configure_logging()
                               ^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/airflow/logging_config.py", line 88, in configure_logging
          from airflow._shared.logging import configure_logging, init_log_folder, translate_config_values
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/airflow/_shared/logging/__init__.py", line 27, in <module>
          from .structlog import configure_logging, init_log_file, init_log_folder
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/airflow/_shared/logging/structlog.py", line 38, in <module>
          from .percent_formatter import PercentFormatRender
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/airflow/_shared/logging/percent_formatter.py", line 29, in <module>
          from structlog.dev import ConsoleRenderer, Styles
      ImportError: cannot import name 'Styles' from 'structlog.dev' (/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/structlog/dev.py). Did you mean: 'types'?

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/sphinx/cmd/build.py", line 414, in build_main
          app = Sphinx(
                ^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/sphinx/application.py", line 266, in __init__
          self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/sphinx/config.py", line 357, in read
          namespace = eval_config_file(filename, tags)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/sphinx/config.py", line 616, in eval_config_file
          raise ConfigError(msg % traceback.format_exc()) from exc
      sphinx.errors.ConfigError: There is a programmable error in your configuration file:

      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/sphinx/config.py", line 601, in eval_config_file
          exec(code, namespace)  # NoQA: S102
          ^^^^^^^^^^^^^^^^^^^^^
        File "/home/runner/work/astronomer-c
```
https://github.com/astronomer/astronomer-cosmos/actions/runs/18850021860/job/53784297603