Enable listener tests for Airflow 3.1 (#2348)
closes: https://github.com/astronomer/astronomer-cosmos/issues/2045

This PR aims to re-enable Cosmos DAG run listener integration tests on
Airflow 3.1 by updating how test `DagRun` objects are created, removing
the prior Airflow 3.1 skip conditions.

**Changes:**
- Updated `create_dag_run` to use `tests.utils.new_test_dag()` for
Airflow 3.1+.
- Removed `skipif(AIRFLOW_VERSION >= 3.1.0)` markers from DAG run
listener tests.
- Relaxed telemetry mock assertions from `call_count == 1` to
`assert_called()`.



------

In **Airflow 3.0**, `DAG.create_dagrun` exists on the `DAG` class:  

https://github.com/apache/airflow/blob/3.0.0/airflow-core/src/airflow/models/dag.py#L1785

In **Airflow 3.1**, the implementation is moved to
`SerializedDAG.create_dagrun`:

https://github.com/apache/airflow/blob/3.1.7/airflow-core/src/airflow/serialization/serialized_objects.py#L3272

This cause error
```
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_success - AttributeError: 'DbtDag' object has no attribute 'create_dagrun'
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_failed - AttributeError: 'DbtDag' object has no attribute 'create_dagrun'
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_success_with_telemetry_metadata - AttributeError: 'DbtDag' object has no attribute 'create_dagrun'
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_failed_with_telemetry_metadata - AttributeError: 'DbtDag' object has no attribute 'create_dagrun'
= 4 failed, 139 passed, 8 skipped, 1229 deselected, 61 warnings in 2120.26s (0:35:20) =
```

https://github.com/astronomer/astronomer-cosmos/actions/runs/21980482831/job/63501602465

-------

When an end-to-end DAG is run with `dag test`, this makes more than one
call to the server.

```
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_success - AssertionError: assert 15 == 1
 +  where 15 = <MagicMock name='emit_usage_metrics_if_enabled' id='140516799005968'>.call_count
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_failed - AssertionError: assert 15 == 1
 +  where 15 = <MagicMock name='emit_usage_metrics_if_enabled' id='140516818848080'>.call_count
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_success_with_telemetry_metadata - AssertionError: assert 15 == 1
 +  where 15 = <MagicMock name='emit_usage_metrics_if_enabled' id='140516813739600'>.call_count
FAILED tests/listeners/test_dag_run_listener.py::test_on_dag_run_failed_with_telemetry_metadata - AssertionError: assert 10 == 1
 +  where 10 = <MagicMock name='emit_usage_metrics_if_enabled' id='140518041445968'>.call_count
= 4 failed, 139 passed, 8 skipped, 1229 deselected, 65 warnings in 2231.59s (0:37:11) =
```


https://github.com/astronomer/astronomer-cosmos/actions/runs/21997675979/job/63561862291