Fix CI main branch Airflow 2.6 tests (#2268)
Cosmos main branch Python 2.6 tests started failing, as observed while
testing Python 3.10, AF 2.6 and dbt 1.11:
```
=========================== short test summary info ============================
ERROR tests/operators/_asynchronous/test_base.py - AttributeError: module 'pyparsing' has no attribute 'DelimitedList'. Did you mean: 'delimitedList'?
ERROR tests/operators/_asynchronous/test_bigquery.py - AttributeError: module 'pyparsing' has no attribute 'DelimitedList'. Did you mean: 'delimitedList'?
ERROR tests/test_example_dags_no_connections.py - AssertionError: assert not {'/home/runner/work/astronomer-cosmos/astronomer-cosmos/dev/dags/simple_dag_async.py': 'Traceback (most recent call la...s.operators._asynchronous.bigquery.DbtRunAirflowAsyncBigqueryOperator. Unable to find the specified operator class.\n'}
 +  where {'/home/runner/work/astronomer-cosmos/astronomer-cosmos/dev/dags/simple_dag_async.py': 'Traceback (most recent call la...s.operators._asynchronous.bigquery.DbtRunAirflowAsyncBigqueryOperator. Unable to find the specified operator class.\n'} = <airflow.models.dagbag.DagBag object at 0x7ffa7ee04910>.import_errors
```

https://github.com/astronomer/astronomer-cosmos/actions/runs/20999444973/job/60365156803

The issue seemed to be conflicting dependencies, particularly the
installation of "httplib2==0.30.0" (failure) instead of
"httplib2==0.31.0" (success)

Example of success after this change:

https://github.com/astronomer/astronomer-cosmos/actions/runs/21002268536/job/60375248518
(cherry picked from commit dbaef2c56087cd0b44c6dc3639db07084d239131)