Reinstall airflow dependency on pydantic>=2.11 for dbt adapater versions 1.6 & 1.9 (#1715)
`apache-airflow-core 3.0.0` requires `pydantic>=2.11.0`, but the
installed dbt adapters in case of version 1.6 and 1.9 install
`pydantic 1.10.22` which make it incompatible.
With `pydantic 1.10.22` we get the below error
```
File "<...>/hatch/env/virtual/astronomer-cosmos/D9FI7Men/tests.py3.11-3.0-1.6/lib/python3.11/site-packages/cadwyn/_utils.py", line 5, in <module>
     from pydantic._internal._decorators import unwrap_wrapped_function
ModuleNotFoundError: No module named 'pydantic._internal'
```
Hence, we re-install pydantic with the required minimum version after
installing dbt adapters in case of 1.6 & 1.9 to be compatible with
Airflow 3 dependencies.

closes: #1708