Use click<8.3.0 for hatch as click 8.3 breaks hatch (#1987)
`click 8.3.0` release broke hatch run.

To fix this issue, we're pinning `click<8.3.0` when installing `hatch`
in the CI pipeline. We will have to wait for `hatch` to release a fix
for the breaking change introduced by `click<8.3.0` (Tracking issue:
https://github.com/pypa/hatch/issues/2050)

Failure run:
https://github.com/astronomer/astronomer-cosmos/actions/runs/17852869985?pr=1987
**Success** run post restricting c`lick<8.3`:
https://github.com/astronomer/astronomer-cosmos/actions/runs/17852830814?pr=1987

We're seeing the following error in CI:
```
 + zstandard==0.25.0
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/hatch/c │
│ li/__init__.py:221 in main                                                   │
│                                                                              │
│   218                                                                        │
│   219 def main():  # no cov                                                  │
│   220 │   try:                                                               │
│ ❱ 221 │   │   hatch(prog_name='hatch', windows_expand_args=False)            │
│   222 │   except Exception:  # noqa: BLE001                                  │
│   223 │   │   import sys                                                     │
│   224                                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/c │
│ ore.py:1462 in __call__                                                      │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/c │
│ ore.py:1383 in main                                                          │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/c │
│ ore.py:1850 in invoke                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/c │
│ ore.py:1246 in invoke                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/c │
│ ore.py:814 in invoke                                                         │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/d │
│ ecorators.py:34 in new_func                                                  │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/hatch/c │
│ li/run/__init__.py:147 in run                                                │
│                                                                              │
│   144 │   elif not env_name:                                                 │
│   145 │   │   env_name = 'system'                                            │
│   146 │                                                                      │
│ ❱ 147 │   ctx.invoke(                                                        │
│   148 │   │   run_command,                                                   │
│   149 │   │   args=[command, *final_args],                                   │
│   150 │   │   env_names=[env_name],                                          │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/c │
│ ore.py:814 in invoke                                                         │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/click/d │
│ ecorators.py:46 in new_func                                                  │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/hatch/c │
│ li/env/run.py:123 in run                                                     │
│                                                                              │
│   120 │   if filter_json:                                                    │
│   121 │   │   import json                                                    │
│   122 │   │                                                                  │
│ ❱ 123 │   │   filter_data = json.loads(filter_json)                          │
│   124 │   │   if not isinstance(filter_data, dict):                          │
│   125 │   │   │   app.abort('The --filter/-f option must be a JSON mapping') │
│   126                                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/json/__init__.py:339  │
│ in loads                                                                     │
│                                                                              │
│   336 │   │   │   │   │   │   │   │     s, 0)                                │
│   337 │   else:                                                              │
│   338 │   │   if not isinstance(s, (bytes, bytearray)):                      │
│ ❱ 339 │   │   │   raise TypeError(f'the JSON object must be str, bytes or by │
│   340 │   │   │   │   │   │   │   f'not {s.__class__.__name__}')             │
│   341 │   │   s = s.decode(detect_encoding(s), 'surrogatepass')              │
│   342                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: the JSON object must be str, bytes or bytearray, not Sentinel
Error: Process completed with exit code 1.
```

related: https://github.com/pypa/hatch/issues/2050