Fix file lock check (#195)
This should resolve the issue that caused us to yank release `0.5.0`.
This was the error that I was getting previously.

```text

  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/utils/file_syncing.py", line 26, in is_file_locked
    fcntl.flock(f, fcntl.LOCK_UN)
ValueError: I/O operation on closed file

```

I was able to replicate the issue locally and resolve it with this
change.