Fix last broken tests
```
cosmos.exceptions.CosmosDbtRunError: dbt invocation completed with errors: orders: Database Error in model orders (models/orders.sql)
  relation "public.stg_orders" does not exist
  LINE 18:     select * from "***"."public"."stg_orders"
                             ^
  compiled code at target/run/altered_jaffle_shop/models/orders.sql
Task instance in failure state
Task start:None end:2026-01-29 11:36:10.637938+00:00 duration:None
Task:<Task(DbtRunLocalOperator): local_example.orders.run> dag:<DAG: cosmos_manifest_selectors_example> dagrun:<DagRun cosmos_manifest_selectors_example @ 2026-01-29 11:36:06.661130+00:00: manual__2026-01-29T11:36:06.661130+00:00, state:running, queued_at: None. externally triggered: False>
Failure caused by dbt invocation completed with errors: orders: Database Error in model orders (models/orders.sql)
  relation "public.stg_orders" does not exist
  LINE 18:     select * from "***"."public"."stg_orders"
                             ^
  compiled code at target/run/altered_jaffle_shop/models/orders.sql
[2026-01-29 11:36:10,667] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cosmos_manifest_selectors_example' AIRFLOW_CTX_TASK_ID='local_example.customers.run' AIRFLOW_CTX_EXECUTION_DATE='2026-01-29T11:36:06.661130+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2026-01-29T11:36:06.661130+00:00'
Task instance is in running state
 Previous state of the Task instance: queued
Current task name:local_example.customers.run state:scheduled start_date:None
Dag name:cosmos_manifest_selectors_example and current dag run status:running
```
https://github.com/astronomer/astronomer-cosmos/actions/runs/21476188465/job/61860709231?pr=2296