Ensure remote target directory are created when copying files when using local directory (#1740)
Ensure remote target directory are created when copying files when using
local directory.

When configuring a remote target directory that points to a local path
while using AIRFLOW ASYNC, like so:

```bash
AIRFLOW__COSMOS__REMOTE_TARGET_PATH=/usr/local/airflow/cosmos
AIRFLOW__COSMOS__REMOTE_TARGET_PATH_CONN_ID=file_default
```

We might face this issue:

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/airflow/cosmos/simple_dag_async__dbt_async/run/jaffle_shop/models/example/my_second_dbt_model.sql'
```

Closes #1739

Co-authored-by: Giovanni Corsetti <155465603+corsettigyg@users.noreply.github.com>
(cherry picked from commit a712c2d93d3c719f8c00a565c7b335d48441d6b1)