Fix `DbtRunLocalOperator.partial()` support (#1609)
Since Cosmos 1.9.0, users who attempted to use:
```
DbtRunLocalOperator.partial(task_id="foo", project_dir="foo")
```

Started facing the issue:
```
File /usr/local/lib/python3.11/site-packages/airflow/models/baseoperator.py:284, in partial(operator_class, task_id, dag, task_group, start_date, end_date, owner, email, params, resources, trigger_rule, depends_on_past, ignore_first_depends_on_past, wait_for_past_depends_before_skipping, wait_for_downstream, retries, queue, pool, pool_slots, execution_timeout, max_retry_delay, retry_delay, retry_exponential_backoff, priority_weight, weight_rule, sla, map_index_template, max_active_tis_per_dag, max_active_tis_per_dagrun, on_execute_callback, on_failure_callback, on_success_callback, on_retry_callback, on_skipped_callback, run_as_user, executor, executor_config, inlets, outlets, doc, doc_md, doc_json, doc_yaml, doc_rst, task_display_name, logger_name, allow_nested_operators, **kwargs)
281 from airflow.models.dag import DagContext
282 from airflow.utils.task_group import TaskGroupContext
--> 284 validate_mapping_kwargs(operator_class, "partial", kwargs)
286 dag = dag or DagContext.get_current_dag()
287 if dag:

File /usr/local/lib/python3.11/site-packages/airflow/models/mappedoperator.py:123, in validate_mapping_kwargs(op, func, value)
121 names = ", ".join(repr(n) for n in unknown_args)
122 error = f"unexpected keyword arguments {names}"
--> 123 raise TypeError(f"{op.name}.{func}() got {error}")

TypeError: DbtRunLocalOperator.partial() got an unexpected keyword argument 'project_dir'`
```

This was introduced given the changes in how Cosmos operators subclass,
that was introduced to allow to dynamically chose which Airflow operator
is run during DAG rendering time.

Closes: #1546

To validate it, we introduced a new small dbt project and an example
DAG, and it can be tested by running:
```
airflow dags test example_task_mapping
```

Co-authored-by: Ash Berlin-Taylor <ash@astronomer.io>
(cherry picked from commit c8c148b14eed74c415b7eb67045c336ffc906e5d)