fix: Dependencies installation with project level variables (#1822)
## Description

Failed at runtime phase during dependencies installation if project
level variables are used
```
dbt deps \
    --target $FLOPPA_TARGET \
    --profiles-dir $FLOPPA_FOLDER \
    --project-dir $FLOPPA_FOLDER
14:43:11  Running with dbt=1.8.9
14:43:11  Encountered an error:
Compilation Error
  Could not render ingestion_date = '{{ var("ingestion_date") }}': Required var 'ingestion_date' not found in config:
  Vars supplied to <Configuration> = {}
```

## Related Issue(s)

## Breaking Change?

No breaking changes

## Checklist

- [ ] I have made corresponding changes to the documentation (if
required)
- [X] I have added tests that prove my fix is effective or that my
feature works

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>