Fix using the `full_refresh` argument in projects that contain tests
Stop forwarding the `full_refresh` argument to dbt commands that do not support it.

Before this change, if users attempted to use:
```
operator_args={"full_refresh": True},
```

In dbt projects with nodes and other resources that do not support the `--full-refresh` flag, the `DbtTaskGroup` or `DbtDag` would fail, causing:

```
airflow.exceptions.AirflowException: Invalid arguments were passed to
DbtTestLocalOperator (task_id: test). Invalid arguments were:
**kwargs: {'full_refresh': True}
```

This issue was originally reported  in Slack:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1696857998959909

Closes: #589

Co-authored-by: Tatiana Al-Chueyr <tatiana.alchueyr@gmail.com>