Support rendering DbtDag in Airflow 3
Add necessary changes so we can render Cosmos `DbtDag` using `LoadMode.DBT_LS` when using Airflow 3 main branch  (commit 9d6bebe9690a3f21a00044c0aeceaded86484a0c).

Previously, we were unable to run the DAG:
```
import os
from datetime import datetime
from pathlib import Path
from airflow.models import Variable

from cosmos import DbtDag, ExecutionConfig, LoadMode, ProfileConfig, ProjectConfig, RenderConfig, TestBehavior

DEFAULT_DBT_ROOT_PATH = Path(__file__).parent.parent.parent.parent / "dev/dags/dbt"
DBT_ROOT_PATH = Path(os.getenv("DBT_ROOT_PATH", DEFAULT_DBT_ROOT_PATH))
DBT_PROJ_DIR = DBT_ROOT_PATH / "jaffle_shop"
DBT_PROFILE_PATH = DBT_PROJ_DIR / "profiles.yml"
DBT_ARTIFACT = DBT_PROJ_DIR / "target"

project_config = ProjectConfig(
    dbt_project_path=DBT_PROJ_DIR,
    project_name="jaffle_shop",
)

profile_config = ProfileConfig(
    profile_name="default",
    target_name="dev",
    profiles_yml_filepath=DBT_PROFILE_PATH,
)

basic_cosmos_dag = DbtDag(
    # dbt/cosmos-specific parameters
    project_config=project_config,
    profile_config=profile_config,
    operator_args={
        "install_deps": True,  # install any necessary dependencies before running any dbt command
        "full_refresh": True,  # used only in dbt commands that support this flag
    },
    # normal dag parameters
    schedule="@daily",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    dag_id="basic_cosmos_dag",
    default_args={
```

It would raise the following exception when we attempted to run `airflow dags reserialize`:
```
i  File "/Users/tati/Code/cosmos-fresh/astronomer-cosmos/cosmos/airflow/graph.py", line 592, in build_airflow_graph
    task_or_group = conversion_function(  # type: ignore
  File "/Users/tati/Code/cosmos-fresh/astronomer-cosmos/cosmos/airflow/graph.py", line 391, in generate_task_or_group
    task >> test_task
  File "/Users/tati/Code/cosmos-fresh/astronomer-cosmos/venv-af3-main/lib/python3.10/site-packages/airflow/sdk/definitions/_internal/mixins.py", line 97, in __rshift__
    self.set_downstream(other)
  File "/Users/tati/Code/cosmos-fresh/astronomer-cosmos/venv-af3-main/lib/python3.10/site-packages/airflow/sdk/definitions/_internal/node.py", line 216, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/Users/tati/Code/cosmos-fresh/astronomer-cosmos/venv-af3-main/lib/python3.10/site-packages/airflow/sdk/definitions/_internal/node.py", line 186, in _set_relatives
    raise ValueError(
ValueError: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(DbtRunLocalOperator): run>, <Task(DbtTestLocalOperator): test>]
```

This issue happened due to an interface change in Airflow 3's `BaseOperator`, that would lead the line:
```
base_operator_args = set(inspect.signature(BaseOperator.__init__).parameters.keys())
```

To return zero arguments.

This was solved by changing the import path:

```
try:  # Airflow 3
    from airflow.sdk.bases.operator import BaseOperator
except ImportError:  # Airflow 2
    from airflow.models import BaseOperator
```

After these changes, we were able to successfully run:
- `airflow dags reserialize`
- `airflow dags test basic_cosmos_dag`