Error when `RenderConfig.invocation_mode` is incorrectly set (#2267)
Make our configuration validation more robust, to guide users when they
misconfigure Cosmos `RenderConfig.invocation_mode`.

This configuration should only be used if dbt is installed in the same
Python virtualenv as Cosmos.

Recently, I observed a customer incorrectly configuring Cosmos as
follows:
```
ExecutionConfig(
  dbt_executable_path=airflowHome + '/dbt_venv/bin/dbt',
  execution_mode=ExecutionMode.WATCHER,
  invocation_mode=InvocationMode.DBT_RUNNER
)
```

Which led to the error:
```
ModuleNotFoundError: No module named 'dbt'
```

This was raised in Cosmos 1.12, when trying to resolve `dbt.version`
```
cosmos/operators/watcher.py:_fallback_to_local_run → build_and_run_cmd → _generate_dbt_flags
```