Detach dbt vars used to render DAGs from the operator args' (#1616)
A DAG that used Jinja templated `operator_args` vars values, that used
to work in Cosmos 1.9.0, stopped working in Cosmos 1.9.1. The DAG looked
like this:
```
cosmos_dag = DbtDag(
    (...)
    operator_args={
        "vars": """\
            {"execution_date_nodash": {{ (triggering_dataset_events.values() | first | first).source_dag_run.execution_date.strftime('%Y%m%d') }}, \
                "execution_date": {{ (triggering_dataset_events.values() | first | first).source_dag_run.execution_date.strftime('%Y-%m-%d') }} }""",
```

Cosmos 1.9.1 was trying to use `operator_args` `dbt_vars` as dbt vars to
during DAG rendering when using `LoadMode.DBT_LS`. This is an example of
a error raised:
```
Broken DAG: [/usr/local/airflow/dags/dbt/dbt_firebase.py]
Traceback (most recent call last): |
File "/usr/local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 266, in run_command
stdout = run_command_with_subprocess(command, tmp_dir, env_vars)
File "/usr/local/lib/python3.12/site-packages/cosmos/dbt/graph.py", line 210, in run_command_with_subprocess raise CosmosLoadDbtException(f'Unable to run {command) due to the error:\n{details]")
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run [/usr/local/airflow/dbt_venv/bin/dbt*, 'Is', '--output', 'json', '--project-dir', '/tmp/tmpvqh98105', '--profiles-dir', '/tmp/cosmos/profile/a430297fc6403bddbfac273a7a67d1ddd676e0e8406 stderr: Usage: dbt Is [OPTIONS]
Try 'dbt Is -h' for help.
Error: Invalid value for '-vars': String "*
(\'execution _date_nodash\": {{ (triggering_dataset_events.values) | first | first).source_dag_run.execution_date.strftime('%Y%m%d*) }}.
l'execution _date\': f{ (triggering_dataset_events.value
stdout: [0m14:12:45 The YAML provided in the --vars argument is not valid.
```

This change may be perceived as breaking, but it is primarily a bug fix.
Users can still use `ProjectConfig(dbt_vars)` to set dbt variables that
should be used for rendering the DAG when using `LoadMode.DBT_LS`.

We're also making it possible to use different values of `operator_args'
vars`, and `RenderConfig` (via `ProjectConfig.dbt_vars`).

Closes: #1618
(cherry picked from commit 53c7efb6ac66b35b20a770bfe08f90b5c7327548)