Add cluster policy for cosmos (#2293)
## Description

Adding a cluster policy that support retries on a different worker queue
for watcher sensor tasks. This does not currently work due to a circular
import issue when applying the cluster policy.


## Breaking Change?

No

## Checklist

- [ ] I have made corresponding changes to the documentation (if
required)
- [ ] I have added tests that prove my fix is effective or that my
feature works

## current issues

Circular import - I think the cluster policy may need to be packaged
separately

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/usr/local/lib/python3.12/site-packages/airflow/__init__.py", line 74, in <module>
    settings.initialize()
  File "/usr/local/lib/python3.12/site-packages/airflow/settings.py", line 781, in initialize
    load_policy_plugins(POLICY_PLUGIN_MANAGER)
  File "/usr/local/lib/python3.12/site-packages/airflow/settings.py", line 200, in load_policy_plugins
    pm.load_setuptools_entrypoints("airflow.policy")
  File "/usr/local/lib/python3.12/site-packages/pluggy/_manager.py", line 416, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/astronomer_cosmos/cosmos/__init__.py", line 17, in <module>
    from cosmos.airflow.dag import DbtDag
  File "/usr/local/airflow/astronomer_cosmos/cosmos/airflow/dag.py", line 11, in <module>
    from cosmos.converter import DbtToAirflowConverter, airflow_kwargs, specific_kwargs
  File "/usr/local/airflow/astronomer_cosmos/cosmos/converter.py", line 35, in <module>
    from cosmos.listeners.task_instance_listener import _get_profile_config_attribute
  File "/usr/local/airflow/astronomer_cosmos/cosmos/listeners/task_instance_listener.py", line 15, in <module>
    from cosmos.operators.base import AbstractDbtBase
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/__init__.py", line 1, in <module>
    from .local import DbtBuildLocalOperator as DbtBuildOperator
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 20, in <module>
    from airflow import DAG
ImportError: cannot import name 'DAG' from partially initialized module 'airflow' (most likely due to a circular import) (/usr/local/lib/python3.12/site-packages/airflow/__init__.py)
```

---------

Co-authored-by: pankajastro <pankaj.singh@astronomer.io>