Solve unittest related to rich logging
FAILED tests/test_log.py::test_rich_logging_with_rich_logging_false - AssertionError: assert 'Hello, world!' in ''

Relates to change in Airflow 3.1 from logging to stdout to structlog