⬆ [pre-commit.ci] pre-commit autoupdate (#1795)
<!--pre-commit.ci start-->
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.11.11 →
v0.11.12](https://github.com/astral-sh/ruff-pre-commit/compare/v0.11.11...v0.11.12)
- ~[github.com/pre-commit/mirrors-mypy: v1.15.0 →
v1.16.0](https://github.com/pre-commit/mirrors-mypy/compare/v1.15.0...v1.16.0)~
<!--pre-commit.ci end-->

Note: We reverted the upgrade of `mirrors-mypy` from 1.15 to 1.16 since
it was raising the exception:
```
mypy-python..............................................................Failed
- hook id: mypy
- exit code: 1

cosmos/operators/local.py:28: error: Module "attr" has no attribute "define"  [attr-defined]
Found 1 error in 1 file (checked 34 source files)

```

Co-authored-by: Tatiana Al-Chueyr <tatiana.alchueyr@gmail.com>
(cherry picked from commit 173bf8d145149d6e33cc2d0d3dfba0e59c5714b5)