Workaround for issue faced by customer in prod
An Astronomer customer that is using Cosmos 1.5 with caching enabled in production is facing failures in their
DAGs once they change those DAGs or dbt projects.

They are using cache based on Airflow Variables.

The error they are facing is:

File /usr/local/lib/python3.11/site-packages/cosmos/dbt/graph.py, line 135, in parse_dbt_ls_output
    unique_id=node_dict[unique_id]
KeyError: 'unique_id'

This change aims to add additional logs and skip nodes that may not contain necessary fields. This will allow us to identify the root cause