Support Airflow 3.1 (#1980)
Apache Airflow 3.1 beta2 was released on [15 September
2025](https://pypi.org/project/apache-airflow/#history). We have been
working on supporting Airflow 3.1 since its initial release on September
25, 2025.

These were some of the issues we faced while attempting to support
Airflow 3.1, seen on the tests run in:

https://github.com/astronomer/astronomer-cosmos/actions/runs/17766456237/job/50490975762

Example of unittests that fail when running:
```
hatch run tests.py3.10-3.1.0b2-1.10:test-cov
```

Errors:
```
FAILED tests/dbt/test_graph.py::test_save_dbt_ls_cache_remote_cache_dir - AttributeError: The module `'airflow.io'` has no attribute `'path'`
FAILED tests/dbt/test_graph.py::test_get_dbt_ls_cache_remote_cache_dir - AttributeError: The module `'airflow.io'` has no attribute `'path'`
FAILED tests/operators/_asynchronous/test_base.py::test_execute_removes_existing_path - AttributeError: The module `'airflow.io'` has no attribute `'path'`
FAILED tests/operators/test_kubernetes.py::test_dbt_kubernetes_operator_handle_warnings[\n        19:48:25  Concurrency: 4 threads (target='target')\n        19:48:25\n        19:48:25  1 of 2 START test dbt_utils_accepted_range_table_col__12__0 ................... [RUN]\n        19:48:25  2 of 2 START test unique_table__uuid .......................................... [RUN]\n        19:48:27  1 of 2 WARN dbt_utils_accepted_range_table_col__12__0 ..................... [WARN in 1.83s]\n        19:48:27  2 of 2 PASS unique_table__uuid ................................................ [PASS in 1.85s]\n        19:48:27\n        19:48:27  Finished running 2 tests, 1 hook in 0 hours 0 minutes and 12.86 seconds (12.86s).\n        19:48:27\n        19:48:27  Completed with 1 warning:\n        19:48:27\n        19:48:27  Warning in test dbt_utils_accepted_range_table_col__12__0 (models/ads/ads.yaml)\n        19:48:27  Got 252 results, configured to warn if >0\n        19:48:27\n        19:48:27    compiled Code at target/compiled/model/models/table/table.yaml/dbt_utils_accepted_range_table_col__12__0.sql\n        19:48:27\n        19:48:27  Done. PASS=1 WARN=1 ERROR=0 SKIP=0 TOTAL=2\n        19:48:27  Command `dbt test` succeeded at 07:50:02.340364 after 43.98 seconds\n        19:48:27  Flushing usage events\n        -True] - TypeError: __init__() missing 1 required positional argument: 'dag_version_id'
FAILED tests/operators/test_kubernetes.py::test_dbt_kubernetes_operator_handle_warnings[\n        19:48:25  Concurrency: 4 threads (target='target')\n        19:48:25\n        19:48:25  1 of 2 START test dbt_utils_accepted_range_table_col__12__0 ................... [RUN]\n        19:48:25  2 of 2 START test unique_table__uuid .......................................... [RUN]\n        19:48:27  1 of 2 PASS 252 dbt_utils_accepted_range_table_col__12__0 ..................... [PASS in 1.83s]\n        19:48:27  2 of 2 PASS unique_table__uuid ................................................ [PASS in 1.85s]\n        19:48:27\n        19:48:27  Finished running 2 tests, 1 hook in 0 hours 0 minutes and 12.86 seconds (12.86s).\n        19:48:27\n        19:48:27  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2\n        -False] - TypeError: __init__() missing 1 required positional argument: 'dag_version_id'
FAILED tests/operators/test_kubernetes.py::test_dbt_kubernetes_operator_handle_warnings[\n        gibberish\n        -False] - TypeError: __init__() missing 1 required positional argument: 'dag_version_id'
FAILED tests/operators/test_kubernetes.py::test_dbt_kubernetes_operator_handle_warnings_noop - TypeError: __init__() missing 1 required positional argument: 'dag_version_id'
FAILED tests/operators/test_local.py::test_run_operator_emits_events_without_openlineage_events_completes - TypeError: __init__() missing 1 required positional argument: 'dag_version_id'
FAILED tests/operators/test_local.py::test_configure_remote_target_path - AttributeError: The module `'airflow.io'` has no attribute `'path'`
FAILED tests/operators/test_local.py::test_upload_compiled_sql_should_upload - AttributeError: The module `'airflow.io'` has no attribute `'path'`
FAILED tests/operators/test_local.py::test_upload_sql_files_creates_parent_directories - AttributeError: The module `'airflow.io'` has no attribute `'path'`
FAILED tests/operators/test_virtualenv.py::test_run_command_without_virtualenv_dir - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/operators/test_virtualenv.py::test_run_command_with_virtualenv_dir - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/athena/test_athena_access_key.py::test_athena_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/bigquery/test_bq_service_account_file.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/clickhouse/test_clickhouse_userpass.py::test_connection_claiming1 - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/databricks/test_dbr_oauth.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/databricks/test_dbr_token.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/duckdb/test_duckdb_user_pass.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/exasol/test_exasol_user_pass.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/exasol/test_exasol_user_pass.py::test_dsn_formatting - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/oracle/test_oracle_user_pass.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/oracle/test_oracle_user_pass.py::test_invalid_connection_type - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/postgres/test_pg_user_pass.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/redshift/test_redshift_user_pass.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_env_variable.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_env_variable.py::test_old_snowflake_format - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_file.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_file.py::test_old_snowflake_format - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_pass.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_pass.py::test_old_snowflake_format - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_pass.py::test_appends_region - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_pass.py::test_appends_host_and_port - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_old_snowflake_format - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_appends_region - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/spark/test_spark_thrift.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/sqlserver/test_standard_sqlserver_auth.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/teradata/test_teradata_user_pass.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/trino/test_trino_base.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/trino/test_trino_base.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/trino/test_trino_certificate.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
FAILED tests/profiles/trino/test_trino_jwt.py::test_connection_claiming - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_file.py::test_profile_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_file.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_file.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_encrypted_privatekey_file.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_pass.py::test_profile_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_pass.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_pass.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_pass.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_decode_private_key_content[base64_encoded] - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_decode_private_key_content[plain_text] - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_profile_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/snowflake/test_snowflake_user_privatekey.py::test_profile_env_vars_with_base64 - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/spark/test_spark_thrift.py::test_spark_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/spark/test_spark_thrift.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/spark/test_spark_thrift.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/spark/test_spark_thrift.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/sqlserver/test_standard_sqlserver_auth.py::test_profile_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/sqlserver/test_standard_sqlserver_auth.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/sqlserver/test_standard_sqlserver_auth.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/teradata/test_teradata_user_pass.py::test_profile_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/teradata/test_teradata_user_pass.py::test_profile_mapping_schema_validation - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/teradata/test_teradata_user_pass.py::test_profile_mapping_keeps_port - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/teradata/test_teradata_user_pass.py::test_profile_mapping_keeps_custom_tmode - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/teradata/test_teradata_user_pass.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/teradata/test_teradata_user_pass.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/teradata/test_teradata_user_pass.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_certificate.py::test_trino_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_certificate.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_certificate.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_jwt.py::test_trino_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_jwt.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_jwt.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_jwt.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_ldap.py::test_trino_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_ldap.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_ldap.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/trino/test_trino_ldap.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/vertica/test_vertica_user_pass.py::test_profile_mapping_selected - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/vertica/test_vertica_user_pass.py::test_profile_mapping_keeps_custom_port - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/vertica/test_vertica_user_pass.py::test_profile_args - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/vertica/test_vertica_user_pass.py::test_profile_args_overrides - AttributeError: module 'airflow.hooks' has no attribute 'base'
ERROR tests/profiles/vertica/test_vertica_user_pass.py::test_profile_env_vars - AttributeError: module 'airflow.hooks' has no attribute 'base'
= 50 failed, 660 passed, 5 skipped, 75 deselected, 2 xfailed, 6 warnings, 138 errors in 63.25s (0:01:03) =
```

I created a follow-up ticket for the last three tests that I didn't fix
in Airflow 3.1:
https://github.com/astronomer/astronomer-cosmos/issues/2045

Closes: https://github.com/astronomer/oss-integrations-private/issues/209