Fix test hash value for Darwin when using Py 3.12.10 (#1786)
This is a test-only change that affects running tests locally in MacOS
and does not affect the actual implementation of Cosmos.

In the past, we observed inconsistencies in how hashing worked across
different platforms (Darwin vs. Linux).

When setting up Cosmos in a brand new laptop that runs MacOS 15.4.1 (Arm
64), I noticed the hash was the same as the CI, and I faced the
following issue when running `hatch run tests.py3.9-2.10-1.9:test-cov`:
```
FAILED tests/dbt/test_graph.py::test_save_dbt_ls_cache - AssertionError: assert '0148da6f5f7fd260c9fa55c3b3c45168' == '391db5c7e1fb90214d829dd0476059a1'

  - 391db5c7e1fb90214d829dd0476059a1
  + 0148da6f5f7fd260c9fa55c3b3c45168
```

In order not to break for others, I'm still supporting the other value
for MacOS.

(cherry picked from commit d8056626336ba40f619db9f86fc26d0c445977dc)